export const GET_ALL_SATELLITES = "GET_ALL_SATELLITES";
export const ADD_SATELLITE = 'ADD_SATELLITE';
export const UPDATE_SATELLITE = 'UPDATE_SATELLITE';
export const EDIT_SATELLITE = 'UPDATE_SATELLITE';
export const SET_SELECTED_SATELLITE = 'SET_SELECTED_SATELLITE';
export const DELETE_SATELLITE = 'DELETE_SATELLITE';
export const SEARCH_SATELLITES = 'SEARCH_SATELLITES';
